### ISSUE TITLE
Add filter option to read n chunks or bytes

### ISSUE THREAD

**Issue by foobarbecue** [cruise-automation/rosbag.js#42]
It would be nice to be able to just read the very beginning of the file.

**Comment by jtbandes** [comment]
It's actually possible to use the [`BagReader` class](https://github.com/cruise-automation/rosbag.js/blob/master/src/BagReader.js) directly (rather than `Bag`) for more low-level access:

https://github.com/cruise-automation/rosbag.js/blob/96ccb2accec29cf476177d2f0d927005cd7600c5/src/BagReader.js#L33-L37

You can see how the Bag class uses it to implement the higher-level functionality: https://github.com/cruise-automation/rosbag.js/blob/96ccb2accec29cf476177d2f0d927005cd7600c5/src/bag.js#L54-L58

**Comment by foobarbecue** [comment]
Wonderful, thanks!
